package-lock.json
package.json
src/app.controller.spec.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/auth/Guards/auth.guard.ts
src/auth/Guards/roles.guard.ts
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/auth.service.ts
src/category/category.controller.ts
src/category/category.module.ts
src/category/category.repository.ts
src/category/category.service.ts
src/category/dtos/createCategory.dto.ts
src/category/dtos/updateCategory.dto.ts
src/clasificacion/clasificacion.controller.spec.ts
src/clasificacion/clasificacion.service.spec.ts
src/clasificacion/dtos/UpdateClasificaciondto.ts
src/clasificacion/dtos/createClasificacion.dto.ts
src/config/typeorm.ts
src/credential/credential.controller.ts
src/credential/credential.entity.ts
src/credential/credential.module.ts
src/credential/credential.repository.ts
src/credential/credential.service.ts
src/data-source.ts
src/decorators/matchPassword.decorator.ts
src/decorators/roles.decorator.ts
src/entities/categories.entity.ts
src/entities/credential.entity.ts
src/entities/file.entity.ts
src/entities/orderDetail.entity.ts
src/entities/orders.entity.ts
src/entities/product.entity.ts
src/entities/users.entity.ts
src/enum/roles.enum.ts
src/enum/statusOrder.enum.ts
src/guards/user-auth.guard.ts
src/interceptors/date-adder.interceptor.ts
src/main.ts
src/migrations/1762678869196-AddUniqueConstraintToCredentialUuid.ts
src/migrations/1762679654961-InitialMigration.ts
src/order_detail/order_detail.controller.ts
src/order_detail/order_detail.module.ts
src/order_detail/order_detail.service.ts
src/orders/dtos/createOrder.dto.ts
src/orders/orders.controller.ts
src/orders/orders.module.ts
src/orders/orders.repository.ts
src/orders/orders.service.ts
src/pago/dtos/CreatePagodto.ts
src/pago/pago.controller.spec.ts
src/pago/pago.service.spec.ts
src/products/dtos/createProduct.dto.ts
src/products/dtos/updateProduct.dto.ts
src/products/products.controller.ts
src/products/products.module.ts
src/products/products.repository.ts
src/products/products.service.ts
src/seed/seed.controller.ts
src/seed/seed.module.ts
src/seed/seed.repository.ts
src/seed/seed.service.ts
src/servicio/servicio.controller.spec.ts
src/tipo-servicio/tipo-servicio.controller.spec.ts
src/users/Dtos/createUser.dto.ts
src/users/Dtos/loginUser.dto.ts
src/users/Dtos/updateUser.dto.ts
src/users/users.controller.ts
src/users/users.entity.ts
src/users/users.module.ts
src/users/users.repository.ts
src/users/users.service.ts
src/usuarios/usuario.entity.ts
src/usuarios/usuarios.controller.spec.ts
src/usuarios/usuarios.controller.ts
src/usuarios/usuarios.module.ts
src/usuarios/usuarios.service.spec.ts
src/usuarios/usuarios.service.ts
test/app.e2e-spec.ts
test/examples/01-basic.spec.ts
test/examples/02-intermediate.spec.ts
tsconfig.json
tsconfig.spec.json
